export const information:Record<string,{title:string;intro:string;sections:[string,string][]}>={
 'contact':{title:'Talk to us.',intro:'Message us on WhatsApp or Instagram about an outfit you like, a custom order or a visit to our atelier in Mohali.',sections:[['Share your occasion','Tell us when you need the outfit and where it needs to go. Send any references you have, and we’ll talk through the design and fabric options.'],['Visiting Mohali','Contact us before planning a visit so we can confirm the address and arrange a suitable time.']]},
 'shipping':{title:'From Mohali to you.',intro:'We ship worldwide from India. Tell us your city and when you need the outfit so we can work out the delivery details with you.',sections:[['Confirm before ordering','Ask us to confirm the making time, dispatch date, carrier, tracking and shipping charges for your destination.'],['International orders','Ask which duties, taxes or customs charges may apply and who will be responsible for them. Confirm these details with the atelier before placing your order.'],['When do you need it?','Tell us when the outfit needs to arrive, allowing time before the event. If the date is close, we’ll check whether the design and delivery schedule are possible.']]},
 'size-and-fit':{title:'Getting the fit right.',intro:'We’ll tell you which measurements we need for your outfit. Send them to us before making begins so we can check the details together.',sections:[['Start with the silhouette','Share the style you want, your preferred lengths and how you like an outfit to fit.'],['Measure with guidance','Ask for the measurement instructions for your chosen design. Confirm the units and check each measurement before sending it.'],['Ordering from a distance','If you’re ordering from another city or country, ask us how to take your measurements. We’ll also discuss fitting or alteration arrangements before you order.']]},
 'returns':{title:'Fit, changes and alterations.',intro:'Ask us about changes, alterations and return conditions before you order. The arrangements need to be agreed for your particular outfit.',sections:[['Before work begins','Discuss the agreed design, measurements, price, timeline and any changes you may need. Ask for the applicable cancellation and return conditions in writing.'],['If the fit needs attention','Contact us with the outfit reference and a description of the issue. Ask about the alteration options, timing and any charges for your location.']]},
 'faq':{title:'Common questions.',intro:'How to order, customise a look and arrange delivery.',sections:[['What does Gulmohar Wears make?','We make suits, lehengas and wedding wear to order in Mohali, Punjab, India.'],['How do I order?','Start on WhatsApp or Instagram. Share the outfit or custom idea, your occasion date and delivery location. Confirm the design, measurements, price and timeline directly with the atelier.'],['Do you ship internationally?','Yes, we ship worldwide from India. We’ll confirm the timing and charges for your destination before you order.'],['Can I customise a photographed look?','Tell us which look you like and what you’d change. We’ll discuss suitable fabrics and design options, then give you a quote.'],['Can you help with a close event date?','Tell us the date in your first message. We’ll check the design and our making schedule before confirming whether we can help.'],['Can I pay on this website?','We’ll agree your order and payment arrangements directly with you. This website does not take online payments.']]},
 'privacy':{title:'Your enquiry and privacy.',intro:'The enquiry form prepares a message in your browser. You decide whether to open WhatsApp and send it to the atelier.',sections:[['What the form does','Form details are held in the current page, without being saved by this website. Opening WhatsApp transfers the prepared message text to WhatsApp. It is not sent to the atelier until you send it there.'],['External conversations','WhatsApp and Instagram have their own privacy practices. Use the channel you are comfortable with and only share the details needed for your enquiry.'],['Questions about your information','Contact Gulmohar Wears directly if you have questions about information shared during an order conversation.']]},
 'terms':{title:'Before you place an order.',intro:'An enquiry starts a conversation. It does not confirm an order or reserve a photographed piece.',sections:[['Agree the details','Confirm the design, fabric, measurements, total price, payment arrangements, making time and delivery plan directly with the atelier.'],['Understand your order conditions','Ask for the applicable cancellation, return and alteration conditions before you make a payment.'],['Photographs and colour','The site shows actual photographed garments. Lighting and screens can affect appearance; confirm important colours and details with the atelier.']]},
};
