import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {looks,findLook,lookMessage} from '@/lib/catalogue';
import {whatsappUrl} from '@/lib/enquiries/messages';
import {ProductGallery} from '@/components/product-gallery';
import {GarmentFilm} from '@/components/film';
import {Arrow} from '@/components/icons';
import {GarmentImage} from '@/components/garment-image';
export const dynamicParams=false;
export function generateStaticParams(){return looks.map(look=>({slug:look.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const look=findLook(slug);return {title:look?.name,description:look?.description};}
export default async function Product({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const look=findLook(slug);if(!look)notFound();return <main id="main"><nav className="breadcrumbs page-width" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/collections">The edit</Link><span>/</span><span>{look.tone}</span></nav><div className="product-layout page-width"><ProductGallery look={look}/><div className="product-description"><p className="eyebrow">THE GULMOHAR EDIT / LOOK {look.number}</p><h1>{look.name}</h1><p className="product-lede">{look.description}</p><p className="quote-note">Made-to-order enquiries<br/><span>Message us for the price and available options.</span></p><a className="button button-primary" href={whatsappUrl(lookMessage(look))} target="_blank" rel="noopener noreferrer">Enquire about this look <Arrow diagonal/></a><Link className="text-link" href={`/custom?look=${look.slug}`}>Make it your own <Arrow diagonal/></Link><div className="product-facts"><h2 className="eyebrow">IN THE PHOTOGRAPHS</h2><ul>{look.features.map(f=><li key={f}>{f}</li>)}</ul></div><details open><summary>Fabric, fit and finishing</summary><p>Ask us about the fabric, embroidery technique and care instructions. We’ll also explain which measurements we need before you order.</p></details><details><summary>Your date and destination</summary><p>Tell us your event date and delivery location. We’ll check availability and confirm the making time, shipping charges and delivery plan.</p></details><p className="product-note">Colour can vary with lighting and your screen. Ask us for a current close-up or video before confirming your choice.</p></div></div>{look.film&&<section className="product-film-section page-width"><div><p className="eyebrow">IN MOTION</p><h2>The way<br/>it <em>moves.</em></h2><p>Watch the olive-gold suit and dupatta in this short film.</p></div><GarmentFilm/></section>}<section className="related-looks page-width"><h2>You might also like.</h2><div>{looks.filter(l=>l.slug!==look.slug).map(l=><Link href={`/products/${l.slug}`} key={l.slug}><GarmentImage id={l.images[0].id} alt={l.images[0].alt} sizes="(max-width:767px) 44vw, 28vw"/><span>{l.name} <Arrow diagonal/></span></Link>)}</div></section></main>;}
