import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {LookList} from '@/components/look-list';
import {Invitation} from '@/components/footer';
import {Arrow} from '@/components/icons';
import {whatsappUrl} from '@/lib/enquiries/messages';
const categories:{[key:string]:{title:string;heading:string;copy:string}}={suits:{title:'Suits',heading:'The suit edit.',copy:'Browse our fuchsia, blue and olive-gold suits. Each gallery shows the full outfit alongside close-ups of the embroidery.'},'wedding-wear':{title:'Wedding wear',heading:'What will you wear to the wedding?',copy:'Have a wedding coming up? Browse these suits, then tell us which event you’re dressing for and any changes you’d like.'},lehengas:{title:'Custom lehengas',heading:'Your lehenga starts here.',copy:'Send us a reference and tell us about the occasion. We’ll discuss the shape, fabric and embroidery, then confirm measurements and a quote.'},'new-this-week':{title:'The current edit',heading:'The current edit.',copy:'Browse the collection below. Message us to ask about other designs and current availability.'}};
export const dynamicParams=false;
export function generateStaticParams(){return Object.keys(categories).map(category=>({category}));}
export async function generateMetadata({params}:{params:Promise<{category:string}>}):Promise<Metadata>{const {category}=await params;return {title:categories[category]?.title,description:categories[category]?.copy};}
export default async function Collection({params}:{params:Promise<{category:string}>}){const {category}=await params;const entry=categories[category];if(!entry)notFound();return <main id="main"><section className={`page-width collection-page ${category==='lehengas'?'commission-page':''}`}><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/collections">The edit</Link><span>/</span><span>{entry.title}</span></nav><div className="page-heading"><p className="eyebrow">GULMOHAR / {category==='lehengas'?'A PERSONAL COMMISSION':'THE CURRENT EDIT'}</p><h1>{entry.heading}</h1><p>{entry.copy}</p></div>{category==='lehengas'?<div className="commission-body"><span className="commission-number" aria-hidden="true">01 → 04</span><div><h2>Tell us about<br/><em>your lehenga.</em></h2><p>Share the occasion date and where you need it delivered. We’ll work through the fabric and design with you, then confirm measurements and delivery details.</p><a className="button button-primary" href={whatsappUrl('Hi Gulmohar, I would like to discuss a custom lehenga. Please help me with design options, fabric, measurements, price and delivery.')} target="_blank" rel="noopener noreferrer">Discuss a custom lehenga <Arrow diagonal/></a><Link className="text-link" href="/custom">Tell us what you have in mind <Arrow diagonal/></Link></div></div>:<><nav className="collection-tabs" aria-label="Collection categories"><Link href="/collections">All looks</Link><Link href="/collections/suits" aria-current={category==='suits'?'page':undefined}>Suits</Link><Link href="/collections/wedding-wear" aria-current={category==='wedding-wear'?'page':undefined}>Wedding wear</Link><Link href="/collections/lehengas">Custom lehengas</Link></nav><LookList/></>}</section><Invitation/></main>;}
