import type {Metadata} from 'next';
import Link from 'next/link';
import {EditorialFilm} from '@/components/editorial-film';
import {GarmentImage} from '@/components/garment-image';
import {CollectionIndex} from '@/components/collection-index';
import {Invitation} from '@/components/footer';
import {Arrow} from '@/components/icons';
import {whatsappUrl} from '@/lib/enquiries/messages';
export const metadata:Metadata={title:'Gulmohar Wears | Bespoke Indian Wear, Mohali',description:'Discover the Gulmohar edit. Bespoke suits, lehengas and wedding wear from Mohali, Punjab. Begin your made-to-order outfit on WhatsApp. Worldwide shipping.'};
export default function Home(){return <main id="main">
 <section className="campaign" aria-labelledby="campaign-title"><div className="campaign-copy"><p className="eyebrow">GULMOHAR WEARS / MOHALI, PUNJAB</p><h1 id="campaign-title">Made for<br/>your<br/><span>occasion.</span></h1><p className="campaign-description">Bespoke Indian wear from Mohali.<br/>Made to order. Shipped worldwide.</p><a className="button button-light" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">Talk to us on WhatsApp <Arrow diagonal/></a><Link className="campaign-discover" href="#current-edit">Browse the collection <span aria-hidden="true">↓</span></Link></div><div className="campaign-images"><EditorialFilm className="campaign-full" id="olive-hero" label="olive-gold hero film" description="Olive-gold suit with a sheer dupatta, filmed against a warm brown backdrop" eager/><div className="campaign-detail"><GarmentImage id="dsc07089" alt="A closer view of the same olive-gold suit, showing the embroidery across the front and sleeve" eager sizes="(max-width: 767px) 30vw, 25vw"/><div><span className="eyebrow">LOOK 01</span><Link href="/products/olive-gold-suit">Olive gold.<span className="caption-desktop"><br/>See the<br/>embroidery.</span> <Arrow diagonal/></Link></div></div></div></section>
 <section className="brand-intro page-width"><p className="eyebrow">MADE TO ORDER IN MOHALI</p><p>Have an outfit in mind?<br/>We can <em>start there.</em></p><div>We make suits, lehengas and wedding wear in Mohali. Send us a reference, or choose a look below and tell us what you’d change. We ship worldwide.</div></section>
 <section id="current-edit" className="current-edit page-width" aria-labelledby="edit-title"><div className="edit-heading"><div><p className="eyebrow">01 / THE CURRENT EDIT</p><h2 id="edit-title">Find a colour<br/><em>you love.</em></h2></div><p>See each suit in full, then take<br/>a closer look at the embroidery.</p><Link className="text-link" href="/collections">Explore all looks <Arrow diagonal/></Link></div><div className="editorial-spread"><figure className="edit-main"><EditorialFilm id="fuchsia-walk" label="fuchsia suit film" description="Fuchsia embroidered suit filmed outdoors as the model walks and lifts the dupatta"/><figcaption><span>02 / FUCHSIA</span><Link href="/products/fuchsia-suit">View the fuchsia suit <Arrow diagonal/></Link></figcaption></figure><div className="edit-companion"><p className="editor-note">Prefer a<br/>softer shade?</p><figure><Link href="/products/blue-suit"><GarmentImage id="dsc07025" alt="Soft blue embroidered suit standing beside a staircase" position="50% 48%" sizes="(max-width: 767px) 67vw, 32vw"/></Link><figcaption><span>03 / SOFT BLUE</span><Link href="/products/blue-suit">View the blue suit <Arrow diagonal/></Link></figcaption></figure><Link className="text-link" href="/products/olive-gold-suit">See the olive-gold suit <Arrow diagonal/></Link></div></div></section>
 <CollectionIndex/>
 <section className="closer-look" aria-labelledby="detail-title"><div className="detail-photo"><GarmentImage id="dsc07046" alt="Olive-gold sleeve and neckline details with repeating embroidered motifs" sizes="(max-width: 767px) 100vw, 50vw"/></div><div className="detail-story"><p className="eyebrow">03 / A CLOSER LOOK</p><h2 id="detail-title">A closer look<br/>at the<br/><em>embroidery.</em></h2><p>The round neckline and sleeves share the same embroidered pattern. The sheer dupatta has fine stripes.</p><div className="detail-pair"><EditorialFilm id="olive-drape" label="olive-gold drape film" description="Seated view of the olive-gold suit, showing the dupatta spread beside the model"/><div><span className="eyebrow">OLIVE-GOLD SUIT</span><p>See how the<br/>dupatta falls.</p><Link className="text-link" href="/products/olive-gold-suit">Explore the look <Arrow diagonal/></Link></div></div></div></section>
 <section className="personal-process page-width" aria-labelledby="process-title"><div className="process-heading"><p className="eyebrow">04 / MADE AROUND YOU</p><h2 id="process-title">Let’s plan<br/><em>your outfit.</em></h2><p>Tell us about the occasion and when you need your outfit. We’ll discuss the design and agree the details with you.</p><Link className="text-link" href="/custom">Start a custom order <Arrow diagonal/></Link></div><ol className="process-list">{[['Tell us about the occasion','Share your event date and where the outfit needs to be delivered. Tell us what you like to wear, too.'],['Choose the design','Send a reference or start with one of our suits. We’ll discuss the shape, colour and fabric options.'],['Agree the details','We’ll confirm the design, measurements, price and making time with you before work begins.'],['Arrange fit and delivery','We’ll talk through fitting arrangements and how your outfit will reach you.']].map(([title,body],i)=><li key={title}><span className="eyebrow">0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></section>
 <Invitation/>
 </main>;}
